# Generated by Django 5.1.4 on 2024-12-24 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_photos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="date",
        ),
        migrations.AddField(
            model_name="event",
            name="date_created",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="photo",
            name="purchased",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="access_code",
            field=models.CharField(default="77d9942351", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="expiry_date",
            field=models.DateField(),
        ),
    ]
