# Generated by Django 5.1.4 on 2024-12-27 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_photos", "0003_remove_photo_purchased_alter_event_access_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="zip_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="event_zips/",
                verbose_name="Carica ZIP",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="original_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nome Originale del File"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="access_code",
            field=models.CharField(
                default="dffeeaf5a7",
                max_length=20,
                unique=True,
                verbose_name="Codice di Accesso",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_created",
            field=models.DateField(auto_now_add=True, verbose_name="Data di Creazione"),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descrizione"),
        ),
        migrations.AlterField(
            model_name="event",
            name="expiry_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data di Scadenza"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nome Evento"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="event_photos.event",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Caricato il"),
        ),
    ]
