# Generated by Django 5.1.4 on 2024-12-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_photos", "0004_event_zip_file_photo_original_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="access_code",
            field=models.CharField(
                default="8e2327b69f",
                max_length=20,
                unique=True,
                verbose_name="Codice di Accesso",
            ),
        ),
    ]
