# Generated by Django 5.1.4 on 2024-12-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_photos", "0005_alter_event_access_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="access_code",
            field=models.CharField(
                default="76305a92ff",
                max_length=20,
                unique=True,
                verbose_name="Codice di Accesso",
            ),
        ),
    ]
