# Generated by Django 5.1.4 on 2024-12-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_photos", "0006_alter_event_access_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="purchased",
            field=models.BooleanField(default=False, verbose_name="Acquistata"),
        ),
        migrations.AlterField(
            model_name="event",
            name="access_code",
            field=models.CharField(
                default="41c47c240f",
                max_length=20,
                unique=True,
                verbose_name="Codice di Accesso",
            ),
        ),
    ]
