# Generated by Django 5.1.4 on 2025-01-17 17:23

import event_photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_photos", "0008_alter_event_access_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="price_per_photo",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Prezzo per Foto",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="access_code",
            field=models.CharField(
                default="c75ace8bf4",
                max_length=20,
                unique=True,
                verbose_name="Codice di Accesso",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="zip_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="event_zips/",
                validators=[event_photos.models.validate_zip_file],
                verbose_name="Carica ZIP",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="file_path",
            field=models.ImageField(upload_to=event_photos.models.upload_to_event),
        ),
    ]
