# Generated by Django 5.1.4 on 2025-01-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_photos", "0009_event_price_per_photo_alter_event_access_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="access_code",
            field=models.CharField(
                default="ff38c0bd45",
                max_length=20,
                unique=True,
                verbose_name="Codice di Accesso",
            ),
        ),
    ]
