# Generated by Django 5.1.4 on 2025-01-19 10:22

import event_photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_photos", "0010_alter_event_access_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="access_code",
            field=models.CharField(
                default=event_photos.models.generate_unique_access_code,
                max_length=20,
                unique=True,
                verbose_name="Codice di Accesso",
            ),
        ),
    ]
