# Generated by Django 5.1.4 on 2025-01-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_photos", "0011_alter_event_access_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
